#==============================================#
# XenJumpPad by RedSMURF: Configuration file #
#==============================================#

# To add a new pad, follow the example below
# [Pad Name]
# PAD_FLAGS                 = a - Active Delay        b - Active Duration

# PAD_SPAWN_CHANCE          = Pad's respawn probability (0.0 = never, 1.0 = always)
# PAD_ACTIVE_DELAY          = Delay in seconds before the pad becomes active at round start
# PAD_ACTIVE_DURATION       = Duration of the active state in seconds
# PAD_ACTIVE_COOLDOWN       = Cooldown in seconds before the pad becomes active again
# PAD_RADIUS                = Trigger radius for launching players
# PAD_STRENGTH              = Launch strength range (min - max)
# PAD_COOLDOWN              = Delay in seconds between consecutive launches on the same player

# To make an pad available in the menu, you must defined at least it's name like this [Pad]
# pad model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/XenJumpPad/jump_pad.mdl
SETTING_DEFAULT_FLAGS           = 0

SETTING_DEFAULT_FRAMERATE       = 1.0
SETTING_DEFAULT_SPAWN_CHANCE    = 1.0
SETTING_DEFAULT_ACTIVE_DELAY    = 5.0 10.0
SETTING_DEFAULT_ACTIVE_DURATION = 30.0 30.0
SETTING_DEFAULT_ACTIVE_COOLDOWN = 5.0 5.0
SETTING_DEFAULT_RADIUS          = 75.0
SETTING_DEFAULT_STRENGTH        = 600.0 750.0
SETTING_DEFAULT_COOLDOWN        = 2.0 3.0

SETTING_PAD_MINS                = -60 -60 -6.0
SETTING_PAD_MAXS                = 60 60 6.0

SETTING_PAD_LOAD                = 1             # Whether to load saved pads data of the current map
SETTING_PAD_CHECK               = 10.0          # Maximum selection distance when checking nearby pads
SETTING_OFFSET_BASE             = 120.0         # Default forward offset when previewing pad placement
SETTING_OFFSET                  = 65.0 900.0    # Default minimum and maximum offset from the player to the pad (MIN MAX)
SETTING_OFFSET_STEP             = 10.0          # Step size when scrolling to move pad forward/backward
SETTING_GHOST_ALPHA             = 120           # Transparency level of the ghost preview model (0 - 255)

SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav
SETTING_SOUND_JUMP              = doors/aliendoor3.wav

SETTING_COLOR_ACTIVE            = 0 255 0
SETTING_COLOR_INACTIVE          = 255 0 0

[Jump Small]
PAD_STRENGTH    = 370.0 420.0

[Small CoolDown]
PAD_COOLDOWN    = 1.0 1.0

[Jump Straight to Xen]
PAD_STRENGTH    = 1700.0 2200.0






